/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.foodshop.view;

import lk.ijse.foodshop.controller.CustomerController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.foodshop.dto.CustomerDTO;
import lk.ijse.foodshop.entity.Customer;

/**
 *
 * @author kushantha
 */
public class CustomerForm extends javax.swing.JPanel {

    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() throws ClassNotFoundException, SQLException {
        initComponents();
        loadAllCustomer();
        loadCustomerId();

    }
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txtCustAddress = new javax.swing.JTextField();
        txtCustName = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCustContact = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblCID = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1110, 760));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(120, 36, 69));
        jLabel1.setText("MANAGE CUSTOMER");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 300, 50));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUST ID", "contact", "Name", "Address"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1110, 370));
        add(txtCustAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 300, 50));
        add(txtCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 300, 50));

        btnClear.setBackground(new java.awt.Color(141, 134, 13));
        btnClear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 100, 40));

        btnAdd.setBackground(new java.awt.Color(141, 134, 13));
        btnAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 100, 40));

        btnUpdate.setBackground(new java.awt.Color(141, 134, 13));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 100, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("CUSTOMER NAME :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("CUSTOMER ADDRESS :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        btnDelete.setBackground(new java.awt.Color(141, 134, 13));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 100, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Untitled-2.jpg"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 970, -1));

        jPanel1.setBackground(new java.awt.Color(41, 39, 40));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8_search_50px_3.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("CUSTOMER CONTACT :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtCustContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustContactActionPerformed(evt);
            }
        });
        txtCustContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustContactKeyReleased(evt);
            }
        });
        add(txtCustContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 300, 50));

        lblId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("N/A");
        lblId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 120, -1));

        lblCID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCID.setText("NEW CUSTOMER ID :");
        add(lblCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            if (txtCustContact != null && txtCustName != null && txtCustAddress != null) {
                String id = lblId.getText();
                String contact = txtCustContact.getText();
                String custName = txtCustName.getText();
                String custAddress = txtCustAddress.getText();

                String checkContact = new CustomerController().checkContact(contact);
                if (checkContact != null) {
                    JOptionPane.showMessageDialog(this, "this phone number is allready exists");
                } else {
                    boolean isAdd = new CustomerController().isAddedCustomer(new CustomerDTO(id, contact, custName, custAddress));

                    if (isAdd) {
                        JOptionPane.showMessageDialog(this, "Added customer");
                        loadAllCustomer();
                        clearText();
                        loadCustomerId();
                    } else {
                        JOptionPane.showMessageDialog(this, "check again");
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "check again");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String id = lblId.getText();
            String contact = txtCustContact.getText();
            String custName = txtCustName.getText();
            String custAddress = txtCustAddress.getText();

            boolean isUpdate = new CustomerController().updateCustomer(new CustomerDTO(id, contact, custName, custAddress));
            if (isUpdate) {
                JOptionPane.showMessageDialog(this, "Updated customer");
                loadAllCustomer();
                clearText();
                loadCustomerId();
            } else {
                JOptionPane.showMessageDialog(this, "check again");
//                }

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int i = tbl.getSelectedRow();
        model = (DefaultTableModel) tbl.getModel();
        lblId.setText(model.getValueAt(i, 0).toString());
        txtCustContact.setText(model.getValueAt(i, 1).toString());
        txtCustName.setText(model.getValueAt(i, 2).toString());
        txtCustAddress.setText(model.getValueAt(i, 3).toString());

        lblCID.setText("Customer ID :");

    }//GEN-LAST:event_tblMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearText();
        lblCID.setText("NEW CUSTOMER ID:");
        try {
            loadCustomerId();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtCustContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustContactKeyReleased

        try {
            String checkContact = new CustomerController().checkContact(txtCustContact.getText());
            if (checkContact != null) {
                JOptionPane.showMessageDialog(this, "This phone number is allready exists");
                txtCustContact.setText("");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtCustContactKeyReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            String id = lblId.getText();
            boolean isDelete = new CustomerController().deleteCustomer(id);
            if (isDelete) {
                JOptionPane.showMessageDialog(this, "Customer deleted");
                clearText();
                loadAllCustomer();
                loadCustomerId();
            } else {
                JOptionPane.showMessageDialog(this, "Try again");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyPressed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

        try {
            model = (DefaultTableModel) tbl.getModel();
            model.setRowCount(0);

            for (CustomerDTO temp : new CustomerController().searchCustomers(txtSearch.getText())) {
                model.addRow(new Object[]{
                    temp.getCustId(),
                    temp.getContact(),
                    temp.getName(),
                    temp.getAddrss()

                });
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtCustContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustContactActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCID;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCustAddress;
    private javax.swing.JTextField txtCustContact;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void loadAllCustomer() throws ClassNotFoundException, SQLException {
        model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        for (CustomerDTO c : new CustomerController().loadAllCustomer()) {
            model.addRow(new Object[]{
                c.getCustId(),
                c.getContact(),
                c.getName(),
                c.getAddrss()

            });
        }
    }

    private void clearText() {
        txtCustAddress.setText("");
        txtCustContact.setText("");
        txtCustName.setText("");
    }

    private void loadCustomerId() throws ClassNotFoundException, SQLException {
        String id = new CustomerController().getLastId();
        if (id == null) {
            lblId.setText("C001");
        } else {
            String split[] = id.split("C");
            int num = Integer.parseInt(split[1]);
            num++;

            if (num < 10) {
                lblId.setText("C00" + num);
            } else if (num < 100) {
                lblId.setText("C0" + num);
            } else {
                lblId.setText("C" + num);
            }

        }
    }
}
