/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.foodshop.view;

import lk.ijse.foodshop.controller.HomeController;
import lk.ijse.foodshop.controller.OrderController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author kushantha
 */
public class HomeForm extends javax.swing.JPanel {

    /**
     * Creates new form HomeForm
     */
    public HomeForm() throws ClassNotFoundException, SQLException {
        initComponents();
        loadAllOrders();
        loadDate();
        loadAllCustomers();
        loadRejectOrders();
        deleteRejectOrders();
        showTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblOrders = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblRejectOrders = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblCustomers = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(37, 128, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(195, 195, 197));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Today Placed Orders");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, 280, 33));

        lblOrders.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblOrders.setForeground(new java.awt.Color(195, 195, 197));
        lblOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrders.setText("Today Orders");
        jPanel1.add(lblOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 280, 33));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 280, -1));

        jPanel2.setBackground(new java.awt.Color(213, 64, 26));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(195, 195, 197));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Today Reject Orders");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, 280, 33));

        lblRejectOrders.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblRejectOrders.setForeground(new java.awt.Color(195, 195, 197));
        lblRejectOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRejectOrders.setText("Today Orders");
        jPanel2.add(lblRejectOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 280, 33));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 280, -1));

        jPanel3.setBackground(new java.awt.Color(37, 128, 86));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(195, 195, 197));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total customers");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, 280, 33));

        lblCustomers.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblCustomers.setForeground(new java.awt.Color(195, 195, 197));
        lblCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomers.setText("Today Orders");
        jPanel3.add(lblCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 280, 33));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 280, -1));

        lblTime.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(195, 195, 197));
        lblTime.setText("8.20 PM");
        add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 80, -1));

        lblDate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(195, 195, 197));
        lblDate.setText("2020/05/21");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/food1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 520, 250, 270));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCustomers;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblOrders;
    private javax.swing.JLabel lblRejectOrders;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables

    private void loadAllOrders() throws ClassNotFoundException, SQLException {
        String date = loadDate();
        int ordersCount = new HomeController().getAllOrders(date);
        if(ordersCount == 0){
            lblOrders.setText("0");
        }
        lblOrders.setText(String.valueOf(ordersCount));
    }
    private String loadDate() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
        String date2 = dateFormat.format(date);
        lblDate.setText(date2);
        return date2;
    }

    private void loadAllCustomers() throws ClassNotFoundException, SQLException {
        String date = loadDate();
        int ordersCount = new HomeController().getAllCustomers();
        if(ordersCount == 0){
            lblCustomers.setText("0");
        }
        lblCustomers.setText(String.valueOf(ordersCount));
    }
    private void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sd = new SimpleDateFormat("hh:mm:ss");
                lblTime.setText(sd.format(d));
            }
        }).start();
    }

    private void loadRejectOrders() throws ClassNotFoundException, SQLException {
        String date = loadDate();
        int ordersCount = new HomeController().rejectOrdersCount(date);
        if(ordersCount == 0){
            lblRejectOrders.setText("0");
        }
        lblRejectOrders.setText(String.valueOf(ordersCount));
    }

    private void deleteRejectOrders() throws ClassNotFoundException, SQLException {
        String date = loadDate();
        String checkDate = new HomeController().checkDate(date);
        if(checkDate != null){
        boolean  ro = new HomeController().deleteOrders(checkDate);
        }
    }
}
